#!/bin/bash
# read-menu: a menu driven system information program
# Exercise in using test rather than the [[]] compound command

clear
echo "
Please Select:
1. Display System Information
2. Display Disk Space
3. Display Home Space Utilization
0. Quit
"

### The following does the same as the below script but using test
read -p "Enter selection [0-3] > "
grep -qE ^[0-3]$ <<< "$REPLY"
if [ $? -eq 0 ]; then
    echo "entered"
    if [ $REPLY -eq 0 ]; then
        echo "Program terminated."
        exit
    fi
    if [ $REPLY -eq 1 ]; then
        echo "Hostname: $HOSTNAME"
        uptime
        exit
    fi
    if [ $REPLY -eq 2 ]; then
        df -h
        exit
    fi
    if [ $result -eq 3 ]; then
        if [ $(id -u) -eq 0 ]; then
            echo "Home Space Utilization (All Users)"
            du -sh /home/*
        else
            echo "Home Space Utilization ($USER)"
            du -sh $HOME
        fi
        exit
    fi
else
    echo "Invalid entry." >&2
    exit 1
fi




### The following uses [[]]
if [[ $REPLY =~ ^[0-3]$ ]]; then
    if [[ $REPLY == 0 ]]; then
	echo "Program terminated."
	exit
    fi
    if [[ $REPLY == 1 ]]; then
	echo "Hostname: $HOSTNAME"
	uptime
	exit
    fi
    if [[ $REPLY == 2 ]]; then
	df -h
	exit
    fi
    if [[ $REPLY == 3 ]]; then
	if [[ $(id -u) -eq 0 ]]; then
	    echo "Home Space Utilization (All Users)"
	    du -sh /home/*
	else
	    echo "Home Space Utilization ($USER)"
	    du -sh $HOME
	fi
	exit
    fi
else
    echo "Invalid entry." >&2
    exit 1
fi
